In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\KIRAN GHANTASALA\Downloads\Churn_Modelling.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
categorical_cols = df.select_dtypes(include=["object"]).columns
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns

In [7]:
categorical_cols

Index(['Surname', 'Geography', 'Gender'], dtype='object')

In [8]:
numerical_cols

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [9]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
for i in categorical_cols:
    df[i] = encoder.fit_transform(df[i])

In [11]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,1115,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,1177,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,2040,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,289,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,1822,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [12]:
x=df.drop("Exited",axis=1)
y=df["Exited"]

In [13]:
x

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1,15634602,1115,619,0,0,42,2,0.00,1,1,1,101348.88
1,2,15647311,1177,608,2,0,41,1,83807.86,1,0,1,112542.58
2,3,15619304,2040,502,0,0,42,8,159660.80,3,1,0,113931.57
3,4,15701354,289,699,0,0,39,1,0.00,2,0,0,93826.63
4,5,15737888,1822,850,2,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,1999,771,0,1,39,5,0.00,2,1,0,96270.64
9996,9997,15569892,1336,516,0,1,35,10,57369.61,1,1,1,101699.77
9997,9998,15584532,1570,709,0,0,36,7,0.00,1,0,1,42085.58
9998,9999,15682355,2345,772,1,1,42,3,75075.31,2,1,0,92888.52
9999,10000,15628319,2751,792,0,0,28,4,130142.79,1,1,0,38190.78

In [14]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,train_size=0.8)

In [16]:
x_train.shape,x_test.shape

((8000, 13), (2000, 13))

In [17]:
y_train.shape,y_test.shape

((8000,), (2000,))

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [19]:
x_train_scaled

array([[ 1.4692775 , -1.24645641,  0.69157533, ...,  0.64920267,
         0.97481699,  1.36766974],
       [-1.19499359,  1.05381124,  0.02931449, ...,  0.64920267,
         0.97481699,  1.6612541 ],
       [-1.15724427,  0.3664786 , -0.5267013 , ...,  0.64920267,
        -1.02583358, -0.25280688],
       ...,
       [ 0.13108128, -1.6259648 ,  0.16979406, ..., -1.54035103,
        -1.02583358, -0.1427649 ],
       [-1.43776677,  1.62852321,  0.28784412, ...,  0.64920267,
        -1.02583358, -0.05082558],
       [ 0.78217054,  0.21718071,  1.14606806, ...,  0.64920267,
         0.97481699, -0.81456811]])

In [20]:
x_test_scaled

array([[ 0.42961263, -0.04416715, -1.67886989, ..., -1.54035103,
        -1.02583358, -1.01960511],
       [-0.11342351,  0.64443214, -0.39920723, ...,  0.64920267,
         0.97481699,  0.79888291],
       [-1.1361185 ,  0.43240018, -1.6871334 , ...,  0.64920267,
        -1.02583358, -0.72797953],
       ...,
       [ 0.98407747,  0.77960199,  0.36103516, ...,  0.64920267,
        -1.02583358, -1.16591585],
       [-1.35638061, -0.02204946,  1.5993803 , ...,  0.64920267,
        -1.02583358, -0.41163463],
       [ 0.66407403, -0.5433811 ,  1.53563326, ...,  0.64920267,
         0.97481699,  0.12593183]])

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential([
    Dense(64, activation="relu", input_shape=(x_train_scaled.shape[1],)),
    Dense(32, activation="relu"),
    Dense(1, activation="sigmoid")  # Regression output
])

c:\Users\KIRAN GHANTASALA\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [38]:
x_train_scaled.shape[1]

13

In [39]:
model.summary()
#13*64+64
#64*32+32
#32*1+1

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,029 (35.27 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6,020 (23.52 KB)

In [ ]:
from tensorflow.keras.optimizers import Adam
model.compile(
    optimizer=Adam(),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [31]:
history = model.fit(
    x_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6670 - loss: 87280.9531 - val_accuracy: 0.7987 - val_loss: 11057.3301
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6783 - loss: 9340.5488 - val_accuracy: 0.7987 - val_loss: 2898.3330
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6666 - loss: 11103.1885 - val_accuracy: 0.7987 - val_loss: 7148.1245
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6722 - loss: 5767.6001 - val_accuracy: 0.7987 - val_loss: 7909.9917
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6670 - loss: 7552.1274 - val_accuracy: 0.2013 - val_loss: 5299.4194
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6798 - loss: 6558.8350 - val_accuracy: 0.7987 - val_loss: 4052.2090
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6764 - loss: 5831.4004 - val_accuracy: 0.2013 - val_loss: 4963.5747
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6650 - loss: 6538.1123 - val_accuracy: 0.7987 - val_loss: 4419.8555
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6669 - loss: 4570.2773 - val_accuracy: 0.7987 - val_loss: 1800.8864
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6802 - loss: 5036.5601 - val_accuracy: 0.7987 - val_loss: 1946.0753
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6767 - loss: 6785.7949 - val_accuracy: 0.7987 - val_loss: 5205.4023
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6739 - loss: 6789.2505 - val_accuracy: 0.7987 - val_loss: 3945.6296
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6734 - loss: 5859.9731 - val_accuracy: 0.7987 - val_loss: 5454.1143
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6784 - loss: 6668.2314 - val_accuracy: 0.7987 - val_loss: 2973.8252
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6841 - loss: 4660.6055 - val_accuracy: 0.7987 - val_loss: 4949.2480
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6750 - loss: 9370.7090 - val_accuracy: 0.4706 - val_loss: 2474.4048
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6689 - loss: 4038.9272 - val_accuracy: 0.7987 - val_loss: 3198.7668
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6714 - loss: 5524.9561 - val_accuracy: 0.7987 - val_loss: 2576.7178
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6736 - loss: 6599.5605 - val_accuracy: 0.7987 - val_loss: 3830.5500
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6730 - loss: 4445.0078 - val_accuracy: 0.2013 - val_loss: 5592.7246
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6731 - loss: 6910.2788 - val_accuracy: 0.7550 - val_loss: 565.8531
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6805 - loss: 4379.7949 - val_accuracy: 0.7987 - val_loss: 5001.6929
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6789 - loss: 5031.7393 - val_accuracy: 0.7987 - val_loss: 1469.6772
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6758 - loss: 4089.7356 - val_accuracy: 0.7987 - val_loss: 1814.8356
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6767 - loss: 4261.6660 - val_accuracy: 0.7987 - val_loss: 2531.2988
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6752 - loss: 5516.5254 - val_accuracy: 0.7987 - val_loss: 4275.1567
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6736 - loss: 3789.3469 - val_accuracy: 0.2013 - val_loss: 4538.3779
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6698 - loss: 3634.1765 - val_accuracy: 0.2013 - val_loss: 4152.0308
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6753 - loss: 4262.4375 - val_accuracy: 0.7987 - val_loss: 4976.0664
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6795 - loss: 4631.8276 - val_accuracy: 0.7987 - val_loss: 1673.2823
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6716 - loss: 4517.1035 - val_accuracy: 0.7881 - val_loss: 551.9078
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6820 - loss: 5167.3003 - val_accuracy: 0.7987 - val_loss: 8360.6260
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6777 - loss: 3943.0071 - val_accuracy: 0.7987 - val_loss: 6327.1118
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6766 - loss: 6015.2515 - val_accuracy: 0.7987 - val_loss: 8666.5615
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6837 - loss: 3836.5769 - val_accuracy: 0.7987 - val_loss: 4328.8833
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6833 - loss: 3331.0007 - val_accuracy: 0.7987 - val_loss: 5128.7329
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6730 - loss: 5005.1035 - val_accuracy: 0.7987 - val_loss: 1064.0564
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6667 - loss: 7117.8257 - val_accuracy: 0.7987 - val_loss: 12979.7090
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6745 - loss: 3422.2971 - val_accuracy: 0.7987 - val_loss: 8090.0283
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6752 - loss: 4397.8975 - val_accuracy: 0.5763 - val_loss: 492.7447
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6747 - loss: 5339.5098 - val_accuracy: 0.2025 - val_loss: 2971.4937
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6858 - loss: 2609.9170 - val_accuracy: 0.2013 - val_loss: 7797.6138
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6689 - loss: 4206.8936 - val_accuracy: 0.7987 - val_loss: 1740.5730
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6834 - loss: 2773.1790 - val_accuracy: 0.7987 - val_loss: 2071.1826
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6698 - loss: 3652.6499 - val_accuracy: 0.7987 - val_loss: 8386.4043
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6819 - loss: 4982.0396 - val_accuracy: 0.4831 - val_loss: 936.8431
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6742 - loss: 2219.6953 - val_accuracy: 0.7987 - val_loss: 3857.4854
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6781 - loss: 5480.2251 - val_accuracy: 0.7987 - val_loss: 1592.6033
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6833 - loss: 3527.6228 - val_accuracy: 0.7987 - val_loss: 2045.3168
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6730 - loss: 3339.8940 - val_accuracy: 0.7987 - val_loss: 9537.5420

In [32]:
model.evaluate(x_test_scaled,y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4725 - loss: 0.7671

[0.7670644521713257, 0.4724999964237213]

In [36]:
y_pred = model.predict(x_test)
print("Predicted Prices:", y_pred[:5])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Predicted Prices: [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [37]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8035